### ISSUE TITLE
Invalid public address

### ISSUE THREAD

**Issue by Livaa** [monero-integrations/monerophp#101]
For some reason, the public addresses i am getting are not valid

`$crypto_note    = new Cryptonote;`
`$hex_seed         = $crypto_note->gen_new_hex_seed();`
`$address            = $crypto_note->address_from_seed($hex_seed);`
`$is_valid_address   = $crypto_note->verify_checksum($address); //is false`

Here is a detailed output :

> hex seed: 73dd6d63f0078e5b22db04b5a4e95247b1620c12762c4f89edea51c76bcb5da8

>public address: 47BBbiKw29U2RAvscPNny5Q96nWEScga9ANoMyKUGRdKbe1Ygzm8BaEiBWBbDMWqUdeAeKjNvE4kPYB7pW7WDdT928

>is valid address: verify_checksum returned false

>private spend key: 3196d3c1e828d6eac2ba5857f2269d76b0620c12762c4f89edea51c76bcb5d08

>private view key: 296a9ddb344a78a10e0b53bdc8855828b6aa72bff266beaea63a09729eea6906

>public spend key: 9288f05f5464bf08785c9298d197908a57ca60858dd9e6380df6e441df55e2cf

>public view key: 166eeca7dff4a7f634a507135edecade33dd2a8654a638ba613ad806177e2c41

Following the tool at https://xmr.llcoins.net/addresstests.html , all the spend/view keys are correct, but the address should be 

>47BBbiKw29U2RAvscPNny5Q96nWEScga9ANoMyKUGRdKbe1Ygzm8BaEiBWBbDMWqUdeAeKjNvE4kPYB7pW7WDdT98QKbKku

not

>47BBbiKw29U2RAvscPNny5Q96nWEScga9ANoMyKUGRdKbe1Ygzm8BaEiBWBbDMWqUdeAeKjNvE4kPYB7pW7WDdT928

It is like Cryptonote::encode_address() based on base58::encode is not correct.
Also i am able to generate a subaddress, i don't know how to verify it, but it may be erroneous as well as it is using base58::encode() too.

`$sub = $crypto_note->generate_subaddress(0, 0, $private_view_key, $public_spend_key);`

Which will generate (based on the hex seed from above)

> 89WJ3xCkoAoMzHXHGKhBxwA2sWXdeczfxESZtBnjA25pF7iXGAu7Ch99VSJeWfFSYdhVpFQhzt6vF3AySXDuNv9VVJfW2BK

System: Ubuntu 18.04
PHP: 7.3.9

**Comment by Livaa** [comment]
Sorry for answering my own issue 5 minutes after opening it ... 
The keccak checksum is missing into the addresses returned by Cryptonote::encode_address()

`$encoded = $this->base58->encode($data);` 

Should be replaced by

`$checksum = $this->keccak_256($data);`
`$encoded = $this->base58->encode($data . substr($checksum, 0, 8));`

**Comment by serhack** [comment]
May you create a pull request? :) I'm a little bit busy

**Comment by Livaa** [comment]
done, have a good day !
