### ISSUE TITLE
offline mnemonic support planned?

### ISSUE THREAD

**Issue by dan-da** [monero-integrations/monerophp#103]
Is there any plan to support using mnemonics without an RPC connection?  Specifically generating a new random mnemonic and reading/validating a mnemonic.

I see there is already offline support for creating addresses and sub-addresses.

**Comment by serhack** [comment]
Hi, 
Thanks for your interest. At the moment I do not have any plan to include this feature since I'm busy with others projects. However it would be not hard to implement this.

Thank you,
Cheers,
SerHack

**Comment by dan-da** [comment]
ok, thanks.  Would you mind outlining how best to attack it?   I might have a go in my free time.   Correct me if I'm wrong, but I don't think there is presently any PHP lib that supports it.

**Comment by dan-da** [comment]
Hi, I made a [tool](https://github.com/dan-da/subaddress-derive-xmr) written in php that works with mnemonics.   For that, I made a [php mnemonics implementation](https://github.com/dan-da/subaddress-derive-xmr/blob/master/src/mnemonic.php).

If you wish, I could integrate the mnemonic class into your library and submit a pull request.
It might make sense to put it into its own separate repo and require via composer.  I would probably do a little refactoring first, such as moving words for each lang into a separate lang file and adding more test cases.   Or if you wanted to just include mnemonic.php directly in your repo, that works also.

**Comment by dan-da** [comment]
ok, now i've broken the mnemonic code out into a [separate repo](https://github.com/dan-da/monero-mnemonic-php), that can be required via composer.

**Comment by serhack** [comment]
Feel free to submit a pull request to our repo! Keep up the great work :- )

**Comment by serhack** [comment]
Implemented!
