### ISSUE TITLE
Use native PHP SHA-3 when available?

### ISSUE THREAD

**Issue by cypherbits** [monero-integrations/monerophp#104]
Hello, I noticed we use a SHA3 class, could we use native PHP SHA-3 when available? Is there anything which prevents us from doing this?

**Comment by serhack** [comment]
We could not use the native php SHA-3 functions since Monero uses a particular modified version of SHA-3 named "Keccak". You can look up for more information about [Keccak-256](https://monerodocs.org/cryptography/keccak-256/).
