### ISSUE TITLE
walletRPC missing refresh() call

### ISSUE THREAD

**Issue by burnside** [monero-integrations/monerophp#106]
Might I suggest making the following addition to walletRPC.php:

```
  /**
   *
   * Refresh the wallet after opening
   *
   * @param  int  $start_height  Block height from which to start    (optional)
   *
   * @return object  Example: {
   *   // TODO example
   * }
   *
   */
  public function refresh($start_height = null)
  {
    $params = array('start_height' => $start_height);
    return $this->_run('refresh', $params);
  }

```

To support the refresh() RPC call as documented here: https://web.getmonero.org/resources/developer-guides/wallet-rpc.html#refresh

Cheers

**Comment by serhack** [comment]
Hey, could you open a PR to get credited? It's simple :- )
Otherwise I'll commit that

**Comment by burnside** [comment]
Sure, I'll give it a try.
