### ISSUE TITLE
Enable SSL validation by default for non loopback connections

### ISSUE THREAD

**Issue by emanuelb** [monero-integrations/monerophp#11]
Currently SSL validation is disabled via:
> curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

https://github.com/monero-integrations/monerophp/blob/7d0b2c3ac0aacfad5de070320f6ee16822d64e14/jsonRPCClient.php#L132

I suggest to:
1. have option to disable/enable SSL validation.
2. disable validation by default if $this->url is loopback address (such as: 127.0.0.1 , localhost, ::1, etc..) as there is no need for SSL in this case (nothing leave the network...)
3. enable validation by default via:
> CURLOPT_SSL_VERIFYHOST, '2'
CURLOPT_SSL_VERIFYPEER, '1'

**Comment by serhack** [comment]
Hello, 

@emanuelb you are right. There is an hack for ssl, because I was  looking for a solution. You gave me one!
I will developing this as soon as possible because I'm travelling :+1: 
Thanks for everything!

**Comment by serhack** [comment]
Implemented.
