### ISSUE TITLE
Some base58.php fixes 

### ISSUE THREAD

**Issue by pandabadger** [monero-integrations/monerophp#110]
Syntax errors:

Line 75:
`if (!is_array($bin) {`
should be:
`if (!is_array($bin)) {`

Line 97:
`if (!is_string($str) {`
should be:
`if (!is_string($str)) {`

Type check error:
Line 220, double is valid.
`if (!is_int($index)) {`
should be:
`if (!is_int($index) && !is_float($index)) { `

When autoloading, an exception will try to load a class named 'MoneroIntegrations\MoneroPhp\Exception' resulting in a class not found error. 
After line 30:
`namespace MoneroIntegrations\MoneroPhp;`
re-add:
`use Exception;`

**Comment by pandabadger** [comment]
@serhack my mistake, the following:

> Line 220, double is valid.
> if (!is_int($index)) {

was intended to be **line 295**, ie. it should be changed in decode_block(). The change to encode_block() may well still apply (as was previously 'integer' || 'double' with gettype()) but I have not tested that one.

**Comment by serhack** [comment]
@pandabadger fixed.
