### ISSUE TITLE
What do I do after "getting started"?

### ISSUE THREAD

**Issue by mstyp** [monero-integrations/monerophp#113]
so i followed the steps in the getting started section, and now i have a web page that looks like the example web page, but the rest of the docs are way above my head. 

I dont know php. I just have a simple html apache website hosted on a debain 10 vps.

I just want a webpage that functions the same as the "merchent view" in the regular gui wallet. Or somethign like the wordpress woocommerce plugin.

**Comment by t-900-a** [comment]
See: https://github.com/monero-project/monero/issues/6404

**Comment by recanman** [comment]
@serhack can you close this?
