### ISSUE TITLE
Be composer/packagist compatible

### ISSUE THREAD

**Issue by emanuelb** [monero-integrations/monerophp#12]
Thus it will be easier to integrate this library into new projects & maintain library upgrades.
for example: have a look at: (similar library?)
https://packagist.org/packages/psychiccat/monero-php
which is currently the only result for searching monero in packagist:
https://packagist.org/search/?q=monero

**Comment by serhack** [comment]
Hello, :+1:
I'd like to develop this feature.
I wouldnt depend on a library  developed 1 year ago, then I started to develop my own.
With this library, you can make every integrations.
Thanks for help

**Comment by serhack** [comment]
https://packagist.org/packages/monero-integrations/monerophp/

:D
