### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by Monerujos** [monero-integrations/monerophp#121]

**Comment by cypherbits** [comment]
Hi, which version of the library are you using?

Are you always using $monero->transfer($receive_amount,$receive_address) ?

**Comment by Monerujos** [comment]
I've tried latest and previous versions versions and results are the same

Other functions fails from time to time but transfer always return "Invalid Request" ( funds transferred )

I have tried different parameters, to the point where there is nothing more to try

Problem is that funds are actually sent and monerod logs indicate no issue

It could be some latency issue but I can't get at bottom of it

**Comment by Monerujos** [comment]
Request: 


{"jsonrpc":"2.0","method":"transfer","params":{"destinations":[{"amount":80000400000,"address":"VALIDADDRESSHERE"}],"mixin":10,"get_tx_key":true,"payment_id":"","account_index":0,"subaddr_indices":"","priority":2,"do_not_relay":false}}; 


Another maintainer of Monero told me that  priority -> 2 make transactions looks a bit more unique on blockchain and that we should fix that

Sniffer response:

HTTP/1.1 200 Ok
Server: Epee-based
Content-Length: 111
Content-Type: application/json
Last-Modified: Tue, 02 Mar 2021 23:17:52 GMT
Accept-Ranges: bytes

{
  "error": {
    "code": -32600,
    "message": "Invalid Request"
  },
  "id": 0,
  "jsonrpc": "2.0"
}HTTP/1.1 200 Ok
Server: Epee-based
Content-Length: 392
Content-Type: application/json
Last-Modified: Tue, 02 Mar 2021 23:17:59 GMT
Accept-Ranges: bytes

{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "amount": 60000600000,
    "fee": 54820000,
    "multisig_txset": "",
    "tx_blob": "",
    "tx_hash": "TX",
    "tx_key": "KEY",
    "tx_metadata": "",
    "unsigned_txset": "",
    "weight": 1452
  }
}


This could be some issue that tor is grouping connections or something similar?
And that with transfer library is getting some delay and only getting first response and with other calls it works most of the time

**Comment by Monerujos** [comment]
Sniffed request:

POST /json_rpc HTTP/1.1
Host: v3.onion:7835
Accept: */*
Accept-Encoding: gzip,deflate
Content-type: application/json
Content-Length: 0

POST /json_rpc HTTP/1.1
Host: v3.onion:7835
Accept: */*
Accept-Encoding: gzip,deflate
Content-type: application/json
Content-Length: 314

{"jsonrpc":"2.0","method":"transfer","params":{"destinations":[{"amount":80000200000,"address":"VALIDADDRESSHERE"}],"mixin":10,"get_tx_key":true,"payment_id":"","account_index":0,"subaddr_indices":"","priority":2,"do_not_relay":false}}

**Comment by Monerujos** [comment]
So the questions is where does this empty request come from and why it doesn't cause problems for functions that take less time to execute?

**Comment by cypherbits** [comment]
Can you confirm you are only calling transfer() once and not any other function before this one?

**Comment by serhack** [comment]
I've spotted some issue with the recent change of "path", and deprecation of "id" field on request. Could you please retest it now?

My demo code works: 

```
<?php
use MoneroIntegrations\MoneroPhp\walletRPC;

// Make sure to display all errors
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once("../monerophp/src/jsonRPCClient.php");
require_once("../monerophp/src/walletRPC.php");

$walletRPC = new walletRPC('127.0.0.1', 1234, false);
$amount = "0.1";
$address = "56bY2v2RJZNEvrKdYuwG73Q2idshQyGc5fV74BZqoVv72MPSBEakPbfWYtQH4PLGhk3uaCjNZ81XJ7o9pimAXzQFCv7bxxf";
$try_transfer = $walletRPC->transfer($amount, $address);
print_r($try_transfer);
```
