### ISSUE TITLE
How to use authorized rpc?

### ISSUE THREAD

**Issue by skkarwasra02** [monero-integrations/monerophp#13]
I have to use --disable-rpc-login in monero-wallet-rpc but i want to use authorized rpc. So how to use username and password in example.php? I have tried monero:password@ip instead of ip in example.php but it's didn't work.  It show '401 Unauthorized' in browser. I want to make explorer and wallet website with free api. Is it safe to use rpc without login? Thanks.

**Comment by serhack** [comment]
Hello,
Thanks for contacting me. First of all, you remember me that I have to update the library with username and password. Until tonight, you should update your library with the new one that support username and password by CURL.
Using wallet rpc without login is safe with RESTRICTED-RPC OPTION ENABLED, else someone can try to move your funds. Better improvements: create a view-only wallet and start your rpc on that.
Cheers
Ps: I'm going to update library, thanks

**Comment by skkarwasra02** [comment]
Great, Thank you so much.

**Comment by serhack** [comment]
Your welcome
