### ISSUE TITLE
Include "get_transfer_by_txid" function

### ISSUE THREAD

**Issue by alvinjoelsantos** [monero-integrations/monerophp#15]
You can call the rpc with:

`curl -X POST http://127.0.0.1:18082/json_rpc \-H 'Content-Type: application/json' \-d '{"jsonrpc":"2.0","id":"0","method":"get_transfer_by_txid","params":{"txid":"<TX_HASH>"}}'`

**Comment by serhack** [comment]
Hello @alvinjoelsantos ,
I'm going to implement that asap!
