### ISSUE TITLE
the class is not found

### ISSUE THREAD

**Issue by YasirNader** [monero-integrations/monerophp#156]
Hello everyone,

i have tried to implement the package in my laravel application, i am using php v8.3 and guzzlehttp v7.x

i tried to connect to the rpc node in my laravel controller but i get the error message that the class i imported was not found. 

ERROR MESSAGE `Class ‘MoneroIntegrations\MoneroPhp\WalletRpc’ not found`

**Comment by BrianHenryIE** [comment]
The actual classname has a lowercase `w`:  https://github.com/monero-integrations/monerophp/blob/25d4c5838b35cbf1fb55170b831e895681a7410a/src/walletRPC.php#L36

That may or may not be the problem. PHP is getting stricter so maybe older versions were more forgiving of this. Hard to know the full problem without a backtrace.

**Comment by YasirNader** [comment]
> The actual classname has a lowercase `w`:
> 
> https://github.com/monero-integrations/monerophp/blob/25d4c5838b35cbf1fb55170b831e895681a7410a/src/walletRPC.php#L36
> 
> That may or may not be the problem. PHP is getting stricter so maybe older versions were more forgiving of this. Hard to know the full problem without a backtrace.

it was indeed because of that, thank you very much for your help! i have a small question, i have problems with the rpc connection, do i need to have an ssl certificate?
