### ISSUE TITLE
monero wallet integaration

### ISSUE THREAD

**Issue by jibinpaul09** [monero-integrations/monerophp#16]
Hello,
    I coudnt get the result from monero wallet after the installation of both wallet and this plug in. I changed the ip and port number in the example.php file.but i coudnt get the expected reply. how can i get the result.is there any additional settings is needed for the proper integration.

**Comment by serhack** [comment]
Are you testing it locally? Could you verify if you can reach the port for Monero Wallet rpc in your browser?

**Comment by jibinpaul09** [comment]
hello,
   Iam testing this plugin in amazon server. when i print_r($monero_daemon); this coe iam getting the below output,

Monero_Payments Object ( [url:Monero_Payments:private] => http://127.0.0.1:18081/json_rpc [client:Monero_Payments:private] => jsonRPCClient Object ( [url:protected] => http://127.0.0.1:18081/json_rpc [is_debug:protected] => [parameters_structure:protected] => array [username:jsonRPCClient:private] => [password:jsonRPCClient:private] => [curl_options:protected] => Array ( [78] => 8 [13] => 8 ) [httpErrors:jsonRPCClient:private] => Array ( [400] => 400 Bad Request [401] => 401 Unauthorized [403] => 403 Forbidden [404] => 404 Not Found [405] => 405 Method Not Allowed [406] => 406 Not Acceptable [408] => 408 Request Timeout [500] => 500 Internal Server Error [502] => 502 Bad Gateway [503] => 503 Service Unavailable ) ) [ip:Monero_Payments:private] => 127.0.0.1 [port:Monero_Payments:private] => 18081 [user] => [password] => )

Does this is because of any protection enabled in my server or anything else. Can you please give me a solution.

**Comment by serhack** [comment]
How did you run Monero Wallet rpc?

**Comment by jibinpaul09** [comment]
Hello,
By using ./monerod command. And i also got the wallet address when i use the ./monero-wallet-cli command

**Comment by serhack** [comment]
You have to run Monero Wallet https://github.com/monero-integrations/monerowp/blob/master/README.md#step-3-setup-your--monero-wallet-rpc

**Comment by jibinpaul09** [comment]
Hello,,

Is there any additional configuration needed in my core walet to connect to the monero plugin.. I need php plug in to do this integration not wordpress. When i trying to connect other plugins i have done come configurations in my wallet.Like that do i need any additional configuration done in my monero wallet? Can you please provide me a solution. Is there any difference in monero-wallet-cli and monero-waller-rpc.. Is there any version problem occure when we integrate this plugin with the core.

**Comment by jibinpaul09** [comment]
hello
 
I installed the monero wallet using the below link

https://www.monero.how/tutorial-how-to-create-a-command-line-monero-wallet

**Comment by serhack** [comment]
Monero Wallet RPC builds a JSON RPC API for managing your wallet by external "calls".
Monero Wallet Command Line Interface is a program for managing your wallet by command line.
