### ISSUE TITLE
Decimal Points

### ISSUE THREAD

**Issue by NanoBytesInc** [monero-integrations/monerophp#17]
This seems to omit the decimal point from all balance/transaction values.

**Comment by NanoBytesInc** [comment]
I could just divide the number by 10^12... but still...

**Comment by serhack** [comment]
The library provides you the RPC response from Monero Wallet RPC Interface. It doesn't omit the decimal point, simply Monero Wallet rpc avoids any misunderstanding for the balance.

I'd like to suggest you the private function _transform for putting the decimal point on a Balance.
