### ISSUE TITLE
sending with hard coded fees

### ISSUE THREAD

**Issue by ja-heller** [monero-integrations/monerophp#19]
Is there any way to use a 'hardcoded' fee, instead a dynamic one, when sending payments?

All the best;

jaheller

**Comment by cryptochangements34** [comment]
Monero uses a dynamic fee algorithm, mostly for the sake of privacy and anonymity so the current options are just priority multipliers. Here is an interesting resource on fees https://getmonero.org/2017/12/11/A-note-on-fees.html
