### ISSUE TITLE
Daemon RPC Wrapper: "Other Methods"

### ISSUE THREAD

**Issue by sneurlax** [monero-integrations/monerophp#34]
Work progressing in [https://github.com/sneurlax/monerophp#feature/rpc](https://github.com/sneurlax/monerophp/tree/feature/rpc) ([src/daemonRPC.php](https://github.com/sneurlax/monerophp/blob/feature/rpc/src/daemonRPC.php))

These methods are accessible via their own route (not `/json_rpc`.  I haven't figured out how to access them using `jsonRPCClient.php` yet.)

**[Other JSON RPC Methods](https://getmonero.org/resources/developer-guides/daemon-rpc.html#other-daemon-rpc-calls):**

 - [x] `/getheight`
 - [x] `/gettransactions`
 - [x] `/is_key_image_spent`
 - [x] `/sendrawtransaction`
 - [x] `/get_transaction_pool`
 - [x] `/stop_daemon`

**Testing:**

 - [ ] `/getheight`
 - [ ] `/gettransactions`
 - [ ] `/is_key_image_spent`
 - [ ] `/sendrawtransaction`
 - [ ] `/get_transaction_pool`
 - [ ] `/stop_daemon`

**Input validation:**

 - [x] `/is_key_image_spent`
 - [x] `/sendrawtransaction`

**Comment by sneurlax** [comment]
@serhack or @cryptochangements34, care to label this "Help wanted" and/or "Good first issue"?

**Comment by sneurlax** [comment]
See 41930b4f4d8b8a49690eb95ce8c63fa3275b12f5 for commit removing these commented-out functions

**Comment by sneurlax** [comment]
See https://github.com/sneurlax/moneronodejs/commit/a1d42bf626b14eb9240b88b370da11fb0901f39c for an example of how to accomplish this

**Comment by serhack** [comment]
I think we should not implement get_height command because we have already implemented via JSON RPC interface. Otherwise, it will be redundant.

**Comment by sneurlax** [comment]
@serhack this can probably be closed as I will most likely be focusing on aiding @recanman's efforts to upgrade/overhaul/migrate the package to a new standard.  I really like how more fundamental crypto functions have been ported to PHP so we can doublecheck certain things without relying upon a daemon.
