### ISSUE TITLE
Unlocked Balance always return "0" After first Payment

### ISSUE THREAD

**Issue by QuantumLeaper** [monero-integrations/monerophp#52]
Hi there,
I have a script running on cronjob, and when sending a payment with this script everything works great. However, for the PHP/RPC to report the correct unlocked_balance again it needs the RPC daemon to be restarted (or the Monero daemon - either works). I'm uncertain why this is happening, the monero-wallet-cli seems to always show the correct unlocked_balance so I think it has something to do with this script and Monero RPC, or maybe just Monero RPC?

**Comment by sneurlax** [comment]
I would ask if you only have one output in your wallet (as if you'd used `sweep_all`, thus every transfer would lock up your entire balance until it's fully confirmed and unlocked again,) but if restarted `monero-wallet-rpc` or `monerod` refreshes your unlocked balance then that probably isn't that case.  You can check with `$walletRPC->export_key_images();` (use `print_r(...)` or similar...) though: you should have one key image per output.  If you only have one key image, you only have one output, and thus every transfer will lock your entire balance.

But if it isn't that, I have to ask if you're using the latest walletRPC.php and are running a 0.12.0.0 "Lithium Luna" daemon (`monerod`) and RPC wallet (`monero-wallet-rpc`.)  While this library should be backwards-compatible with 0.11.1.0 (except for the new calls, of course,) your issue miiight be a version mismatch issue?

You could also try using `rescan_spent()` before checking your balance.

Are you using multisig?  Any more information about your platform (OS, version, etc.) and setup (local full Monero node? remote node? etc.) could help

**Comment by sneurlax** [comment]
If none of the above sounds relevant or makes any progress, just share as much info as you can: are you on mainnet, testnet, or stagenet?  Could you share a code snippet like the `transfer()` call?  Are you running a local webserver?  Is this wrapper on the same machine as the node it uses?  And so on.  I'm very interested in any issue

**Comment by QuantumLeaper** [comment]
I was testing on the testnet with 0.12.0.0 and rolled back to mainnet for 0.11.1.0. I tried using `rescan_spent() `which wasn't changing anything. However, instead of running monerod and monero-wallet-rpc in standard GNU screen sessions, it seems to work flawlessly with PM2. Which is weird.. haha, anyhow, thanks!
