### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by sneurlax** [monero-integrations/monerophp#57]
In #54 I let an errant `$new_amount` slip in, which was undefined and caused `transfer` calls to fail.  A comprehensive unit testing suite (or at least having example.php test each and ever method) would have caught this issue.

**Comment by sneurlax** [comment]
@serhack this can probably be closed but I am looking thru the overhaul from @recanman to make sure that either A) there are unit tests or B) I help add some/more/test them

**Comment by recanman** [comment]
Yes, this can be closed. The RPC library is being separated, forking a library that has full integration testing already.

**Comment by serhack** [comment]
Good
