### ISSUE TITLE
get_transfers refuses to work with or without parameters

### ISSUE THREAD

**Issue by Codivorous** [monero-integrations/monerophp#59]
It's really weird. I've tried with all sorts of combinations of parameters, but it only returns an empty array. I decided to settle on incoming_transfers for the time being, and that worked but it didn't seem to filter by subaddress, when I had the subaddress index, for example '3', fed to it.

Am I doing something wrong? I'm calling the functions with $WalletRPC->get_transfers().

I appreciate any help! :)

**Comment by sneurlax** [comment]
Hey, someone in IRC also mentioned this problem but when we looked into it, it "magically" solved itself for them, so I'm very interested in hearing about your issue and setup: are you on 0.12.0.0 "Lithium Luna"?  Are you using a local or remote node?  Let me look into this on my end and I may come back with more questions, but the more information you can give, the better!

**Comment by sneurlax** [comment]
PS, the docs *do* say the following:

```
   * Look up transfers
   *
   * @param  array   $input_types      Array of transfer type strings; possible values include 'all', in', 'out', 'pending', 'failed', and 'pool'  (optional)
```

Check the code if you have an issue, but this really should have worked with just a string as an input--I just fucked up that bit of code :)  Thank you again and please let me know if you have any other issues

**Comment by Codivorous** [comment]
Thanks for the quick work @sneurlax!

**Comment by Codivorous** [comment]
Unfortunately, this did not fix the issue completely. While the function now doesn't crash, I still can't actually get it to work.

This is the wallet that I am serving. As you can see, it has plenty of transfers:
![bilde](https://user-images.githubusercontent.com/37982122/38190478-a42c245e-3664-11e8-8bd9-91d082e8a899.png)

The RPC wallet is running, and (hopefully) working:
![bilde](https://user-images.githubusercontent.com/37982122/38190516-d84393c6-3664-11e8-8cab-b0da9dc0eb86.png)

This is the entire code snippet I am trying to run:
![bilde](https://user-images.githubusercontent.com/37982122/38190582-33e44b8a-3665-11e8-93b3-8eb5f6535433.png)

And then I get this output:
![bilde](https://user-images.githubusercontent.com/37982122/38190571-2b8728e0-3665-11e8-9632-932f30236c01.png)

Running it without any parameters doesn't do anything either:
![bilde](https://user-images.githubusercontent.com/37982122/38190612-559e8a9c-3665-11e8-82ff-2b4f4eefae7c.png)

Same output. I hope I provided enough information for you to understand my issue :p

**Comment by sneurlax** [comment]
@serhack could you reopen this issue?  I'm on it.

**Comment by sneurlax** [comment]
@Codivorous, could you try passing `get_transfers(['in'])` and/or `get_transfers('in')`?  `all` isn't a thing (I am making it so now.)

**Comment by sneurlax** [comment]
I can tell it's not a thing from `on_get_transfers` in https://github.com/monero-project/monero/blob/master/src/wallet/wallet_rpc_server.cpp ...

**Comment by Codivorous** [comment]
It does indeed work when you specify "in" - so the issue here is that "all" doesn't exist, even though it's the default and is also specified in the documentation. Thank you for your help again @sneurlax!

**Comment by sneurlax** [comment]
I am opening a pull request now to add this functionality.  Perhaps it was in a previous version of monero-wallet-rpc -- if you need it, it should become functional soon

**Comment by sneurlax** [comment]
Merged, `all` should work now
