### ISSUE TITLE
packagist integration => old version in composer

### ISSUE THREAD

**Issue by mzk** [monero-integrations/monerophp#66]
The latest version on the packagist https://packagist.org/packages/monero-integrations/monerophp#dev-master is 16b39cd4a89571720f0caf447470c982965c35eb but on the github is the commit hash b9aed56b641f6a977cbef03317ebfe221ae77f06 .

**Comment by sneurlax** [comment]
Paging @serhack

**Comment by serhack** [comment]
Updated.
