### ISSUE TITLE
Multiple open wallets can not be made

### ISSUE THREAD

**Issue by samedceylan** [monero-integrations/monerophp#76]
Multiple open wallets can not be made. This ridiculous is using the last purse
in the website;
Amy getbalance request
Jones getbalance request
Mark getbalance request
Lee getbalance request
At the same time, OpenWallet is involved

**Comment by serhack** [comment]
Hi Samedceylan,
Monero Wallet RPC interface does not support this feature then I am going to close this ticket since Monero PHP library aims to give to developers a connection between RPC API interface and your PHP application.

Thank you
