### ISSUE TITLE
open/create wallet with viewkey

### ISSUE THREAD

**Issue by itssteven** [monero-integrations/monerophp#77]
Does the RPC support this? Or would I need to shell_exec(?) my way through `monero-wallet-cli --generate-from-view-key` and then use the rpc to open_wallet?

**Comment by serhack** [comment]
Hi,
I am sorry for the late answer. I think you can't create or open a only-view wallet by RPC, but probably I am wrong.

**Comment by sneurlax** [comment]
I wonder if the new mymonero lightwallet could help with this?  is that true, @vtnerd, and if so, if that something the lightwallet can do?

**Comment by serhack** [comment]
Any updates?

**Comment by grcasanova** [comment]
It has been implemented, check now
