### ISSUE TITLE
Two request make this error.

### ISSUE THREAD

**Issue by reliefs** [monero-integrations/monerophp#80]
After two request i start to get this error, did this not happen a few weeks ago?

018-11-29 00:41:46.706 [RPC0]  ERROR   wallet.wallet2  src/wallet/wallet2.cpp:4582     !is_keys_file_locked(). THROW EXCEPTION: error::wallet_internal_error

**Comment by cryptochangements34** [comment]
That is an issue with the rpc wallet itself and should therefore be reported to monero-project/monero
