### ISSUE TITLE
Use code stype

### ISSUE THREAD

**Issue by vladyslavstartsev** [monero-integrations/monerophp#84]
Thank you for the library. It's awesome because it helps me to work with monero more easily.

But during looking at the code, I've found that code does not look very pretty (at least to me).
What I want is to encourage use of code styles. The best one that I see at the moment is https://github.com/doctrine/coding-standard ( with we can configure)

**Comment by serhack** [comment]
Thank you, I can confirm a a partial rewritten is necessary. The problem is I do not have a lot of time for this since I'm studying.

**Comment by vladyslavstartsev** [comment]
> Thank you, I can confirm a a partial rewritten is necessary. The problem is I do not have a lot of time for this since I'm studying.

@serhack I can make PRs if you want

**Comment by recanman** [comment]
@vladyslavstartsev (if you're still active), do you have recommendations on a code style? I've never used one with PHP.
PRs would be helpful.
