### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by vladyslavstartsev** [monero-integrations/monerophp#85]
this code is dead since php version is required to be at least 5.6

https://github.com/monero-integrations/monerophp/blob/72fe8b073e0ad9e05b3e644fc126f70b574d4967/src/jsonRPCClient.php#L216

**Comment by vladyslavstartsev** [comment]
also why is file `subaddress.php` has also `base58`|`ed25519`|`SHA3` classes? this doesn't make sense for me

**Comment by serhack** [comment]
Great question. cc @cryptochangements34 he's the author of that commit.
