### ISSUE TITLE
Example.php can't find daemonRPC class

### ISSUE THREAD

**Issue by BarneyChambers** [monero-integrations/monerophp#91]
Thanks for the API. I have cloned and run this code, but it seems that for some reason your example.php file cannot find the daemonRPC class? When running the code I get this error 

Fatal error: Uncaught Error: Class 'daemonRPC' not found in /var/www/html/monerophp/example.php:11 Stack trace: #0 {main} thrown in /var/www/html/monerophp/example.php on line 11

**Comment by serhack** [comment]
Any updates?

**Comment by BarneyChambers** [comment]
I ended up just making my own API
