### ISSUE TITLE
"No error" json_last_error_msg

### ISSUE THREAD

**Issue by davemodis** [monero-integrations/monerophp#93]
jsonRPCClient.php on line 107 make false error when json_last_error_msg returns "No error" message.
**fix:**
`$this->validate( !is_null($jsonErrorMsg) && $jsonErrorMsg !== 'No error' , $jsonErrorMsg . ': ' . $responseMessage);`

**Comment by serhack** [comment]
Hey, thank you for the fix. Next time you could use the precious "Pull request" feature :- ) so your contribution will be counted on your Github profile.
