### ISSUE TITLE
Response Http Error - 401 Unauthorized

### ISSUE THREAD

**Issue by randy86** [monero-integrations/monerophp#94]
hello i have problem, when i using the getbalance function etc rpc work fine, but when i using the transfer function the result is eror Response Http Error - 401 Unauthorized but the transaction in wallet is successfull.  how to fixed the error response ?

Thank you

**Comment by serhack** [comment]
Hi! Did you set up a digest user for authentication? For test, you may disable it by adding the '--disable-rpc-login'.
