### ISSUE TITLE
Is this library compatible with Monero's new transaction address format?

### ISSUE THREAD

**Issue by BarneyChambers** [monero-integrations/monerophp#99]
Monero recently did a hardfork to move away from the payment ID model, and implemented a new address format that included payment id in the address. Has this been implemented yet in this library? Thanks

**Comment by serhack** [comment]
Hi, I think you're meaning integrated address (with the payment ID encrypted). Yes, the PHP library supports the method call [make_integrated_address](https://github.com/monero-integrations/monerophp/blob/master/src/walletRPC.php#L991)

**Comment by BarneyChambers** [comment]
Sorry I think my question was unclear. How do we use $walletRPC->transfer() with integrated addresses? If it just the same as using the transfer() function on normal transactions that do not have payment IDs?

**Comment by cypherbits** [comment]
Actually, integrated addresses were there from before and they will be removing them too. This is for anonymity. We will have to use subaddresses.

**Comment by serhack** [comment]
As @cypherbits wrote, integrated address are being deprecated ([see this issue](https://github.com/monero-project/monero/issues/3772) and [this article](https://web.getmonero.org/2019/06/04/Long-Payment-ID-Deprecation.html) for more information). 

To send a transaction using RPC with an integrated address:

1. Call the method split_integrated_address (as params, you have to pass the integrated address). This will return the details of the integrated address (payment id, public address and a bool called "is_subaddress").

2. Call transfer method with the details you obtained before.
